### PR TITLE
A fair bit of stuff in order to get the user add forms in, including model changes

### PR DESCRIPTION
**Pull request by stringfellow**
WIll need to pip install -r requirements.txt for the forms bits.

Quite a lot in this is not yet functional, but might be worth merging to get things rolling.

@jimr @davea

### CODE REVIEW

**Comment by stringfellow** [comment]
Take a look at the load_gqahi_nutrients mgmt cmd to see how the new models should work, also the docstr on the Test model.

**Comment by jimr** [comment]
Is there a data migration or is it just worth restarting with a fresh database?

**Comment by stringfellow** [comment]
To be honest I couldn't be bothered to make one... Just dropped all rows and then re ran it... Bit naughty but thought it might be quicker than munging the existing rows around.

**Comment by stringfellow** [comment]
Hum. Updated the param/observed filter but can't get the date ones to play ball with the DateTimeWidget - I don't think it likes empty values, but I can't make it take the initial…

**Comment by jimr** [comment]
I think it's a problem with `django-filter` + `django-datetime-widget`, but I'm not sure which is to blame. There was an open ticket on `django-datetime-widget` that I've left a comment on, so maybe we'll get to the bottom of it:

https://github.com/asaglimbeni/django-datetime-widget/issues/5

**Pull request merged**
